-Multiple IT environments added. -Support for additional: suites and file systems on root partition (ext4, xfs, reiserfs and jfs). -Grub2 installed on /boot parition. -Added ngetty for Ubuntu-based appliances. -NTP configuration via ntpdate. -Various bash completions improved. -Regeneration of ssh keys on first boot. -Added support for readahead and insserv (lenny). -Two partitions created on deployment: boot and the root. -Added trap to release devices on error. -Kernel modules deletion improved. -Download first, install later the packages to save resources. -Added ACPI for power management. -Some packages are only unpacked on deployment creation and configured on first boot.

diff --git a/bin/blss-commons b/bin/blss-commons
--- a/bin/blss-commons
+++ b/bin/blss-commons
@@ -24,25 +24,37 @@
 #   Common functionalities for all blss scripts. Include this script on with the 
 # 'source' command.
 
-# Supported 
+## Support 
 declare -A SUPPORTED_DISTROS=(["debian"]="debian" ["ubuntu"]="ubuntu")
-declare -A SUPPORTED_SUITES=(["squezed"]="squezed" ["lenny"]="lenny" ["maverick"]="maverick" ["lucid"]="lucid" )
-declare -A DISTRO_PER_SUITE=(["lenny"]="debian" ["squezed"]="debian" ["lucid"]="ubuntu" ["maverick"]="ubuntu")
-declare -A SUITES_PER_DISTRO=(["debian"]="squezed, lenny" ["ubuntu"]="maverick, lucid")
+declare -A SUPPORTED_SUITES=(["squeeze"]="squeeze" ["lenny"]="lenny" ["natty"]="natty" ["maverick"]="maverick" ["lucid"]="lucid")
+declare -A DISTRO_PER_SUITE=(["lenny"]="debian" ["squeeze"]="debian" ["lucid"]="ubuntu" ["maverick"]="ubuntu"  ["natty"]="ubuntu")
+declare -A SUITES_PER_DISTRO=(["debian"]="squeeze, lenny" ["ubuntu"]="natty, maverick, lucid")
 declare -A SUPPORTED_ARCHS=(["amd64"]="amd64" ["i386"]="i386")
 declare -A SUPPORTED_HYPERVISORS=(["esxi"]="esxi" ["kvm"]="kvm" ["qemu"]="qemu" ["vbox"]="vbox" ["vmserver"]="vmserver" ["vmw6"]="vmw6" ["xen"]="xen")
+SUPPORTED_CPU=$(echo {1..32})
+declare -A DISTRO_LOCALE_GEN_PATH=(["debian"]="/etc/locale.gen" ["ubuntu"]="/var/lib/locales/supported.d/local")
+declare -A SUPPORTED_FILESYSTEMS=(["ext3"]="ext3" ["ext4"]="ext4" ["btrfs"]="btrfs" ["jfs"]="jfs" ["xfs"]="xfs" ["reiserfs"]="reiserfs")
+declare -A GRUB_MODS_PER_FILESYSTEM=(["ext3"]="" ["ext4"]="" ["btrfs"]="" ["jfs"]="jfs" ["xfs"]="xfs" ["reiserfs"]="reiserfs")
+declare -A EXTRA_PACKAGES_PER_FILESYSTEM=(["ext3"]="" ["ext4"]="" ["btrfs"]="btrfs-tools" ["jfs"]="jfsutils" ["xfs"]="xfsprogs" ["reiserfs"]="reiserfsprogs")
 
-# Defaults
+## Kernel image package per distro and architecture
+declare -A DISTRO_LNX_IMG_PKG=(["debian", "amd64"]="linux-image-amd64" ["debian", "i386"]="linux-image-686" ["ubuntu", "amd64"]="linux-image-server" ["ubuntu", "i386"]="linux-image-server")
+
+## Common packages
+declare -A EXTRA_PKGS_DISTROS=(["debian"]="" ["ubuntu"]="ubuntu-keyring")
+declare -A EXTRA_PKGS_SUITES=(["squeeze"]="readahead-fedora" ["lenny"]=" insserv readahead dash" ["natty"]="readahead-fedora" ["maverick"]="readahead-fedora" ["lucid"]="readahead-fedora")
+declare -A READAHEAD_PER_SUITE=(["squeeze"]="readahead-fedora" ["lenny"]="readahead" ["natty"]="readahead-fedora" ["maverick"]="readahead-fedora" ["lucid"]="readahead-fedora")
+declare -A ACPI_PER_DISTRO=(["debian"]="acpi-support-base" ["ubuntu"]="acpi")
+
+## Defaults
 declare -A DEF_INSTALL_MIRROR=(["debian"]="http://ftp.debian.org/debian" ["ubuntu"]="http://archive.ubuntu.com/ubuntu")
-DEF_BOOT_MENU_TIMEOUT=0
 DEF_PACKAGES=""
 DEF_HYPERVISOR=kvm
 DEF_CPU=1
-DEF_MEMORY=64
-DEF_SIZE=512
-
-# Profile mirror files
-DEF_EV=".blss"
+DEF_MEMORY=128
+DEF_SIZE=1024
+DEF_ROOT_FILESYSTEM=ext3
+DEF_EV=".blss" # Profile mirror files
 
 # process the environment settings
 proc_ev() {
@@ -52,6 +64,7 @@ proc_ev() {
   ( [ -d "$ev" ] && [ -r "$ev" ] ) || (err "Environment '$ev' doesn't exists or isn't a readable directory" >&2 && exit 1)
 }
 
+## Log and error messages
 inf() {
   cat << EOT
 >>> INFO: $1 >>>
@@ -79,19 +92,28 @@ err_non_r() {
 _stepnum=0
 step() {
   cat << EOT
->>>
 >>> STEP $_stepnum: $1 >>>
 >>>
 EOT
   _stepnum=$(( $_stepnum + 1 ))
 }
 
-# Trim leading and ending spaces
+## Utils 
+
+# trim leading and ending spaces
 trim_spcs() {
   printf "${1#"${1%%[![:space:]]*}"}"
 }
 
-# regex
+# convert form hexadecimal to decimal
+hx2dc() {
+  bc << EOT
+ibase=16; $(echo $1 | tr '[:lower:]' '[:upper:]')
+EOT
+}
+
+## Regex matching
+
 match_ip() {
   [[ "$1" =~ ^([01]?[[:digit:]][[:digit:]]?|2[0-4][[:digit:]]|25[0-5])\.([01]?[[:digit:]][[:digit:]]?|2[0-4][[:digit:]]|25[0-5])\.([01]?[[:digit:]][[:digit:]]?|2[0-4][[:digit:]]|25[0-5])\.([01]?[[:digit:]][[:digit:]]?|2[0-4][[:digit:]]|25[0-5])$ ]]
 }
@@ -102,7 +124,8 @@ match_positive_num() {
   [[ "$1" =~ ^[1-9]+[[:digit:]]*$ ]]
 }
 
-# Define wroot based commands
+## Chroot based commands
+
 chr() {
   env \
 -u LC_ALL \
@@ -111,8 +134,77 @@ LANGUAGE="$plang_ctry:$pbaselang" \
 TZ="$tzon" \
   sudo chroot $wroot $@
 }
-chr_apt_get() {
-  chr env DEBIAN_FRONTEND=noninteractive apt-get --force-yes -y $@
+# Acquire::Check-Valid-Until=false => See http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=595801
+apt_get_update() {
+  chr << EOT
+apt-get -o 'Acquire::Check-Valid-Until=false' update
+EOT
+}
+apt_get_download() {
+  chr << EOT
+apt-get --yes --force-yes --no-install-recommends --download-only install $@
+EOT
+}
+apt_get_install() {
+  bind_dev_proc
+  bind_dev_pts
+  chr << EOT
+export DEBIAN_FRONTEND=noninteractive 
+apt-get --yes --force-yes --no-install-recommends install $@
+EOT
+  unbind_dev_pts
+  unbind_dev_proc
+}
+apt_get_unpack() {
+  chr << EOT
+export DEBIAN_FRONTEND=noninteractive 
+dpkg --unpack /var/cache/apt/archives/${1}_*.deb
+EOT
+}
+apt_get_unpack_all() {
+  chr << EOT
+export DEBIAN_FRONTEND=noninteractive 
+dpkg --unpack /var/cache/apt/archives/*.deb
+EOT
+}
+apt_get_dist_upgrade() {
+  bind_dev_proc
+  bind_dev_pts
+  chr << EOT
+export DEBIAN_FRONTEND=noninteractive 
+apt-get --yes --force-yes --no-install-recommends dist-upgrade $@
+EOT
+  unbind_dev_pts
+  unbind_dev_proc
+}
+apt_get_purge() {
+  bind_dev_proc
+  bind_dev_pts
+  chr << EOT
+export DEBIAN_FRONTEND=noninteractive 
+apt-get --yes --force-yes purge $@ || true
+EOT
+  unbind_dev_pts
+  unbind_dev_proc
+}
+apt_get_autoremove() {
+  bind_dev_proc
+  bind_dev_pts
+  chr << EOT
+apt-get --yes --force-yes autoremove
+EOT
+  unbind_dev_pts
+  unbind_dev_proc
+}
+apt_get_clean() {
+  chr << EOT
+apt-get --yes --force-yes clean
+EOT
+}
+apt_get_autoclean() {
+  chr << EOT
+apt-get --yes --force-yes autoclean
+EOT
 }
 
 # When use linux-image-server the command depmod fails due to the path
@@ -122,16 +214,6 @@ chr_apt_get() {
 # STDOUT. For now use the this command instead of 'uname -r'
 kver() {
   chr find /boot -maxdepth 1 -type f | grep -m 1 /boot/vmlinuz | sort -r | sed 's/\/boot\/vmlinuz-//'
-}
-
-# Tmp working directory
-tmp_mk() { 
-  _tmp=$(mktemp -d) && inf "Created '$_tmp' directory"
-}
-
-# Tmp cleanup
-tmp_rm() {
-  sudo rm -rf "$_tmp" && inf "Deleted '$_tmp' directory"
 }
 
 # Copies a first boot script to the bootstrapped system a places an script call
@@ -170,6 +252,9 @@ cp_mirror_file() {
     # directory replaces "/" and " " with "_" to form an unique local name 
     local dst=/etc/apt/sources.list.d/$(dirname "$mf" | tr "/ " "__")_$(basename "$mf" | tr " " "_")  
     sudo cp "$mf" "${wroot}""${dst}" && inf "Copied mirror file at: '$dst'" 
+    chr << EOT
+chmod a+r "$dst"
+EOT
   else
     warn "No mirror file found at '$mf'"
   fi
@@ -199,48 +284,6 @@ enable_root_passwd() {
 root:$ROOTPASSWD
 EOT
   inf "Root password prompt was enabled";
-}
-
-# Bind (re-mount) devices on wroot
-bind_devs() {
-  sudo mount --bind /dev "$wroot"/dev && inf "Bounded '/dev' device"
-  sudo mount -t proc proc "$wroot"/proc && inf "Bounded 'proc' device"
-  sudo mount --bind /dev/pts "$wroot"/dev/pts && inf "Bounded '/dev/pts' device"
-}
-
-# Unbind shared devices
-unbind_devs() {
-  sudo umount "$wroot"/dev/pts 2>/dev/null && inf "Unbounded '/dev/pts' device" || true
-  sudo umount "$wroot"/proc 2>/dev/null && inf "Unbounded 'proc' device" || true
-  sudo umount "$wroot"/dev 2>/dev/null && inf "Unbounded '/dev' device" || true
-}
-
-# trap cmd to unbind mounted devices on error
-_unbind_on_err(){
-	local rc=${1:-''}
-	if [[ -z "$rc" ]] ; then
-		rc=$?
-	fi
-  unbind_devs
-	local alt_rc=$?
-	(( alt_rc != 0 )) && rc=$alt_rc
-	trap - INT TERM EXIT
-	exit $rc
-}
-
-# Import a conf file
-imp_conf() {
-  local conf="$1"
-  if [ -e "$conf"  ] ; then 
-    if [ -r "$conf" ] ; then 
-      . "$conf" && inf "Imported conf file '$conf'"
-    else
-      err "Could not import conf file '$conf'" ;
-      exit 1;
-    fi
-  else
-    warn "Non existing conf file '$conf'" ;
-  fi
 }
 
 # setup the hostname
@@ -338,7 +381,7 @@ install_user_pkgs() {
   step "Install user specified packages"
   if [ -n "$pkgs" ] ; then
     inf "Install user specified packages";
-    chr_apt_get install $pkgs
+    apt_get_install $pkgs
   else
     inf "No packages to install"
   fi
@@ -360,5 +403,414 @@ proc_lcl() {
 # process timezone
 proc_tzon() {
   tzon=$(find /usr/share/zoneinfo/ -type f -print | sed -e 's/\/usr\/share\/zoneinfo\///' -e 's/posix\///' -e 's/right\///' | egrep -m 1 ^$tzon$) || ( err_non_sup timezone >&2 && exit 1 )
+}
+
+# Import a conf file
+imp_conf() {
+  local conf="$1"
+  if [ -e "$conf"  ] ; then 
+    if [ -r "$conf" ] ; then 
+      . "$conf" && inf "Imported conf file '$conf'"
+    else
+      err "Could not import conf file '$conf'" ;
+      exit 1;
+    fi
+  fi
+}
+
+## Temporal working directory
+
+tmp_mk() { 
+  _tmp=$(mktemp -d) && inf "Created '$_tmp' directory"
+}
+tmp_rm() {
+  sudo rm -rf "$_tmp" && inf "Deleted '$_tmp' directory"
+}
+
+## Device handling
+
+bind_dev() {
+  sudo mount --bind /dev "$wroot"/dev && inf "Bounded '/dev' device"
+}
+unbind_dev() {
+  sudo umount "$wroot"/dev && inf "Unbounded '/dev' device"
+}
+bind_dev_proc() {
+  sudo mount -t proc proc "$wroot"/proc && inf "Bounded 'proc' device"
+}
+unbind_dev_proc() {
+  sudo umount "$wroot"/proc && inf "Unbounded 'proc' device"
+}
+bind_dev_pts() {
+  sudo mount --bind /dev/pts "$wroot"/dev/pts && inf "Bounded '/dev/pts' device"
+}
+unbind_dev_pts() {
+  sudo umount "$wroot"/dev/pts && inf "Unbounded '/dev/pts' device"
+}
+bind_devs() {
+  bind_dev
+  bind_dev_proc
+  bind_dev_pts
+}
+unbind_devs() {
+  unbind_dev_pts
+  unbind_dev_proc
+  unbind_dev
+}
+# trap cmd to unbind mounted devices on error
+_unbind_on_err(){
+	local rc=${1:-''}
+	if [[ -z "$rc" ]] ; then
+		rc=$?
+	fi
+  unbind_dev_pts || true
+  unbind_dev_proc || true
+  unbind_dev || true
+	local alt_rc=$?
+	(( alt_rc != 0 )) && rc=$alt_rc
+	trap - INT TERM EXIT
+	exit $rc
+}
+
+## Module handling
+
+# See http://wiki.debian.org/KernelModuleBlacklisting
+#
+# NOTE: Some builtin modules like cdrom cannot be removed via modprobe -r, but
+# they can be blacklisted
+#
+# NOTE: The redirection in 'modprobe -r \$mod 2>/dev/null' is due to a WARNING message
+# See http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=517954   
+
+# remove and the modules (no blacklist) 
+mod_rm() {
+  cat << EOF
+for mod in $@ ; do
+  if modinfo \$mod &>/dev/null ; then   
+    rm \$(modinfo -n \$mod) ;
+  fi
+done
+EOF
+}
+
+# remove the modules in a directory (no blacklist)
+mod_rmdir() {
+  cat << EOF
+for mod in $(chr find /lib/modules/$(kver)/kernel/$1 -type f -path *.ko -exec basename {} .ko \; 2>/dev/null | awk -v ORS=" " '{NF=NF; print $0}') ; do 
+  rm \$(modinfo -n \$mod)
+done
+EOF
+}
+
+# remove and blacklist the modules 
+mod_purge() {
+  cat << EOF
+for mod in $@ ; do
+  if modinfo \$mod &>/dev/null ; then   
+    echo "blacklist \$mod" >> /etc/modprobe.d/floppy.conf ;
+    rm \$(modinfo -n \$mod) ;
+  fi
+done
+EOF
+}
+
+# purge base modules not used very often in server environment 
+purge_base_mods() {
+  chr << EOT
+cat >> /etc/modprobe.d/floppy.conf << EOF
+
+# Blacklist modules not used very often in server environment
+EOF
+$(mod_purge \
+  floppy \
+  ide-floppy \
+  ide-tape \
+  cdrom \
+  ide_cd_mod \
+  snd-pcsp \
+  pcspkr \
+  psmouse \
+  usb-storage \
+  usbcore \
+  uhci_hcd \
+  ehci_hcd)
+EOT
+}
+
+rm_extra_mods() {
+  # firewire
+  chr << EOT
+$(mod_rm \
+  ieee1394 \
+  pcilynx \
+  ohci1394 \
+  video1394 \
+  raw1394 \
+  sbp2 \
+  dv1394 \
+  eth1394 \
+  firewire-ohci \
+  firewire-net \
+  firewire-core \
+  firewire-sbp2)
+rm -f /lib/modules/$(kver)/modules.ieee1394map
+EOT
+
+  # atm
+  chr << EOT
+$(mod_rm \
+  zatm \
+  uPD98402 \
+  ambassador \
+  horizon \
+  iphase \
+  suni \
+  fore_200e \
+  eni \
+  idt77252 \
+  solos-pci \
+  atmtcp \
+  firestream \
+  lanai \
+  he)
+EOT
+
+  # auxdisplay
+  chr << EOT
+$(mod_rm \
+  ks0108 \
+  cfag12864b \
+  cfag12864bfb)
+EOT
+
+  # xen
+  chr << EOT
+$(mod_rm \
+  xen-blkfront \
+  xen-netfront \
+  netxen_nic \
+  xen-kbdfront \
+  xen-fbfront \
+  xenfs \
+  evtchn)
+EOT
+
+  # bluetooth
+  chr << EOT
+$(mod_rm \
+  bnep \
+  cmtp \
+  hidp \
+  rfcomm \
+  sco \
+  l2cap \
+  bluetooth \
+  toshiba_bluetooth \
+  bt3c_cs \
+  btmrvl_sdio \
+  hci_vhci \
+  bluecard_cs \
+  bcm203x \
+  btsdio \
+  dtl1_cs \
+  bfusb \
+  bpa10x \
+  btusb \
+  btmrvl \
+  btuart_cs \
+  ath3k \
+  hci_uart)
+EOT
+
+  # WM Family
+  # WM831x DC-DC Setup Converter, http://www.wolfsonmicro.com/documents/uploads/misc/en/WAN0228.pdf
+  # WM8350 Stereo CODEC with Integrated Power Management, http://www.wolfsonmicro.com/products/power_management/WM8350/
+  # WM8400 Stereo CODEC with Integrated Power Management, http://www.wolfsonmicro.com/products/power_management/WM8400/
+  # WM8739) # Stereo ADC, http://www.wolfsonmicro.com/products/adcs/WM8739/
+  # WM8775) # Stereo ADC with 4 input selector, http://www.wolfsonmicro.com/products/adcs/WM8775/
+  # WM8994 Multi-Channel CODEC with 3 digital audio interfaces, http://www.wolfsonmicro.com/products/audio_hubs/WM8994/
+  # WM97xx Touchscreen, etc, http://www.wolfsonmicro.com/media_centre/item/wolfson_unleashes_dual_codec/
+  chr << EOT
+$(mod_rm \
+  leds-wm831x-status \
+  leds-wm8350 \
+  wm831x_backup \
+  wm831x_bl \
+  wm831x-dcdc \
+  wm831x-gpio \
+  wm831x-hwmon \
+  wm831x-isink \
+  wm831x-ldo \
+  wm831x-on \
+  wm831x_power \
+  wm831x_wdt \
+  wm8350-gpiolib \
+  wm8350-hwmon \
+  wm8350_power \
+  wm8350-regulator \
+  wm8350_wdt \
+  wm8400-core \
+  wm8400-regulator \
+  wm8739 \
+  wm8775 \
+  wm8994-gpio \
+  wm8994-regulator \
+  wm97xx-ts)
+EOT
+
+  # leds
+  chr << EOT
+$(mod_rm \
+  leds-alix2 \
+  leds-mc13783 \
+  leds-net5501 \
+  ledtrig-backlight \
+  leds-88pm860x \
+  ledtrig-heartbeat \
+  leds-bd2802 \
+  leds-ss4200 \
+  ledtrig-default-on \
+  leds-lp3944 \
+  leds-dac124s085 \
+  ledtrig-gpio \
+  leds-da903x \
+  led-class \
+  leds-gpio \
+  dell-led \
+  leds-pca9532 \
+  leds-pca955x \
+  leds-lt3593 \
+  ledtrig-timer \
+  leds-regulator \
+  leds-adp5520)
+EOT
+
+  # memstick
+  chr << EOT
+$(mod_rm \
+  memstick \
+  mspro_block \
+  jmb38x_ms \
+  tifm_ms)
+EOT
+
+  # mfd: Multi-Function Device
+  # # Silicon Motion SM501
+  # TODO: Verify these modules
+  chr << EOT
+$(mod_rm \
+  sm501 \
+  pcf50633-adc \
+  htc-pasic3 \
+  rdc321x-southbridge \
+  janz-cmodio \
+  ab3100-otp \
+  ucb1400_core \
+  lpc_sch \
+  mc13783-core \
+  timberdale \
+  pcf50633-gpio \
+  tps65010 \
+  pcf50633 \
+  tps6507x)
+EOT
+
+  # mmc: MultiMediaCard subsystem, http://www.kernel.org/doc/Documentation/mmc/
+  chr << EOT
+$(mod_rm \
+  sdio_uart \
+  mmc_block \
+  via-sdmmc \
+  sdhci-pltfm \
+  mmc_spi \
+  tifm_sd \
+  sdhci \
+  cb710-mmc \
+  sdhci-pci \
+  wbsd \
+  sdricoh_cs)
+EOT
+
+  # regulator: Regulator, http://www.kernel.org/doc/htmldocs/regulator.html
+  chr << EOT
+$(mod_rm \
+  mc13783-regulator \
+  bq24022 \
+  tps65023-regulator \
+  virtual \
+  tps6507x-regulator \
+  max1586 \
+  max8649 \
+  max8660 \
+  max8925-regulator \
+  lp3971 \
+  da903x \
+  ab3100 \
+  pcf50633-regulator \
+  userspace-consumer)
+EOT
+
+  # uwb: Linux Ultra-Wide-Band stack, as well as drivers for Wireless USB Host Controller drivers, http://www.linuxuwb.org/thewiki/Linux-UWB+WUSB+WiNET
+  chr << EOT
+$(mod_rm \
+  wlp \
+  i1480-dfu-usb \
+  i1480u-wlp \
+  i1480-est \
+  whc-rc \
+  hwa-rc \
+  umc \
+  uwb \
+  whci)
+EOT
+}
+
+# remove other various module directories
+rm_various_mod_dirs() {
+  # more drastically remove
+  chr << EOT
+$(mod_rmdir drivers/media)
+$(mod_rmdir drivers/cdrom)
+$(mod_rmdir drivers/input/gameport)
+$(mod_rmdir drivers/input/joystick)
+$(mod_rmdir drivers/input/mouse)
+$(mod_rmdir drivers/input/touchscreen)
+$(mod_rmdir drivers/parport)
+$(mod_rmdir drivers/telephony)
+$(mod_rmdir sound)
+$(mod_rmdir drivers/isdn)
+$(mod_rmdir drivers/usb)
+$(mod_rmdir drivers/net/bluetooth)
+$(mod_rmdir net/bluetooth)
+$(mod_rmdir drivers/net/ieee80211)
+$(mod_rmdir net/ieee80211)
+$(mod_rmdir drivers/net/ipx)
+$(mod_rmdir net/ipx)
+$(mod_rmdir drivers/net/mac80211)
+$(mod_rmdir net/mac80211)
+$(mod_rmdir drivers/net/wireless)
+$(mod_rmdir net/wireless)
+$(mod_rmdir drivers/net/x25)
+$(mod_rmdir net/x25)
+$(mod_rmdir drivers/net/usb)
+$(mod_rmdir drivers/net/can/usb)
+$(mod_rmdir drivers/ieee1394)
+$(mod_rmdir drivers/firewire)
+EOT
+}
+
+# regenerarte modules.dep
+reg_modules_dep() {
+  chr << EOT
+depmod -a
+update-initramfs -u
+EOT
+}
+
+# cleanup empty modules directories
+cleanup_mod_dirs() {
+  chr << EOT
+find /lib/modules/ -type d -empty -delete
+EOT
 }
 
diff --git a/bin/lxd b/bin/lxd
--- a/bin/lxd
+++ b/bin/lxd
@@ -1,4 +1,4 @@
-#!/bin/bash -ex
+#!/bin/bash -e
 #
 # WELCOME TO BLSS
 #
@@ -54,8 +54,6 @@ SYNOPSIS
 
 DESCRIPTION
 
-  TODO: argument it more. explain DEPLOYMENT_ROOT...
-
   lxd creates a virtual disk in qcow2 format and a libvirt config file from a clone root directory (/) located at CLONE_ROOT. The resulting .qcow2 and .xml files can be used with virsh to define a virtual machine.  
 
 GENERAL OPTIONS
@@ -63,7 +61,7 @@ GENERAL OPTIONS
     Show this help
 
   --clone-root CLONE_ROOT
-    The root directory of the spwecific clone to be loaded into the virtual disk. This parameter is mandatory.
+    The root directory of the specific clone to be loaded into the virtual disk. This parameter is mandatory.
 
 HYPERVISOR OPTIONS
 
@@ -80,6 +78,9 @@ DISK OPTIONS
 
   --size SIZE
     Hard disk size in megabytes. Defaults to ${DEF_SIZE}.    
+
+  --root-filesystem ROOT_FILESYSTEM
+    The root (/) partition filesystem format. Supported file systems are: ${SUPPORTED_FILESYSTEMS[*]}.
 
 EXAMPLES
 
@@ -109,7 +110,8 @@ clone-root:,\
 hypervisor:,\
 cpu:,\
 memory:,\
-size: \
+size:,\
+root-filesystem: \
 -- "$@")
 if [ $? != 0 ] ; then 
   usage >&2 ; 
@@ -126,7 +128,8 @@ unset \
   c_hypervisor \
   c_cpu \
   c_memory \
-  c_size
+  c_size \
+  c_root_filesystem
 
 declare -A c_os 
 while true; do
@@ -152,6 +155,9 @@ while true; do
     --size)
       c_size=${2:?$(err_non_empty $1)} ;
       shift 2 ;;
+    --root-filesystem)
+      c_root_filesystem=${2:?$(err_non_empty $1)} ;
+      shift 2 ;;
     --) 
       shift ; 
       break ;;
@@ -160,12 +166,13 @@ while true; do
   esac
 done
 
-# target is the remaining
+# deployment root is the remaining
 c_deployment_root=$(trim_spcs "$@")
-c_deployment_root=${c_deployment_root:?$(err_non_empty DEPLOYMENT_ROOT)}
+droot=${c_deployment_root:?$(err_non_empty DEPLOYMENT_ROOT)}
+if [ -e "$droot" ] ; then
+  [ "$(find "$droot" -maxdepth 1 -type d -empty )" != "$droot" ] && err "DEPLOYMENT_ROOT command line option shall be an existing empty directory or a non-existing directory" >&2 && exit 1 || true
+fi
 
-# target is the remaining
-c_clone_root=${c_clone_root:?$(err_non_empty --clone-root)}
 
 unset c_os
 
@@ -177,22 +184,25 @@ unset \
   hypervisor \
   cpu \
   memory \
-  size
+  size \
+  root_filesystem
 
 # import general env opts
 imp_conf "$ev"/lxd.conf
 
-# clone root 
+# clone root
 croot=${c_clone_root:-$clone_root}
-if [ -n "$croot" ] ; then
-  croot=$(realpath "$croot") || ( err "--clone-root/clone_root command line/conf file option shall be an existing non-empty directory containing a clone system" >&2 && exit 1 ) ;
-  [ "$(sudo find "$croot" -maxdepth 0 -type d -empty)" != "" ] && err "--clone-root/clone_root command line/conf file option shall be an existing non-empty directory containing a clone system" >&2 && exit 1 || true
+croot=${croot:?$(err_non_empty --clone-root)}
+croot=$(realpath "$croot") || ( err "--clone-root/clone_root command line/conf file option shall be an existing non-empty directory containing a clone system" >&2 && exit 1 ) ;
+empty=$(find "$croot" -maxdepth 0 -type d -empty)
+if [ "$empty" != "" ] ; then
+  err "--clone-root/clone_root command line/conf file option shall be an existing non-empty directory containing a clone system" >&2 && exit 1
 fi
 
 # hypervisor: command line may override the value imported from the 
 # environment, if the option is missing use the default value, finally verify if 
 # the value is supported.    
-hyv=${c_hypervisor:-$hyv} 
+hyv=${c_hypervisor:-$hypervisor} 
 if [ -n "$hyv" ] ; then
   hyv=${SUPPORTED_HYPERVISORS[$hyv]} ;
   hyv=${hyv:?$(err_non_sup hypervisor)} ;
@@ -230,11 +240,17 @@ else
   sz=$DEF_SIZE ;
 fi
 
-# deployment root
-droot=${c_deployment_root}
-if [ -e "$droot" ] ; then
-  [ "$(find "$droot" -maxdepth 1 -type d -empty )" != "$droot" ] && err "DEPLOYMENT_ROOT command line option shall be an existing empty directory or a non-existing directory" >&2 && exit 1 || true
+# root-filesystem: command line may override the value imported from the 
+# environment, if the option is missing use the default value, finally verify if 
+# the value is supported.    
+rootfs=${c_root_filesystem:-$root_filesystem} 
+if [ -n "$rootfs" ] ; then
+  rootfs=${SUPPORTED_FILESYSTEMS[$rootfs]} ;
+  rootfs=${rootfs:?$(err_non_sup root-filesystem root_filesystem)} ;
+else
+  rootfs=$DEF_ROOT_FILESYSTEM ;
 fi
+
 mkdir -p "$droot"
 
 inf "Detected environment '$ev'. All options were took from the environment conf files. Command line options override environment options" ;
@@ -267,41 +283,51 @@ step "Create a new disklabel"
 # "mac", "msdos", "pc98", or "sun".
 sudo parted --script "$droot"/disk.img mklabel msdos
 
-step "Make an ext3 primary partition on disk"
-# TODO: check this
-#   Warning: The resulting partition is not properly aligned for best performance.
-# Make a part-type partition with filesystem fs-type (if specified), 
-# beginning at start and ending at  end  (by default in megabytes).  
-# fs-type can be one of "fat16", "fat32", "ext2", "HFS", "linux-swap",
-# "NTFS",  "reiserfs",  or  "ufs".   part-type  should be one of 
-# "primary", "logical", or "extended".
-dend=$(( $sz - 1))
-sudo parted --script -- "$droot"/disk.img mkpart primary ext3 0 $dend
- 
-step "Add device map: /dev/mapper/XYZ"
-# Create device maps from partition tables.
-#  -a     Add partition mappings
-#  -l     List partition mappings that would be added -a
-details=$(sudo kpartx -av "$droot"/disk.img) 
+step "Make partitions on disk"
+sudo parted --script -- "$droot"/disk.img mkpart primary 1049kB 64MB
+sudo parted --script "$droot"/disk.img set 1 boot on
+sudo parted --script -- "$droot"/disk.img mkpart primary 64MB 100%
 
-map=$(printf "$details" | awk '{print $3}')
-inf "Device map: /dev/mapper/$map"
+_release_devs(){
+  # Detach the file or device associated with the specified loop device. 
+  # See the above explantaion of loop devices
+  sudo umount "$wroot"/boot && inf "Unmounted $wroot"/boot
+  sudo umount "$wroot" && inf "Unmounted $wroot"
 
-dev=$(printf "$details" | awk '{print $8}')
-inf "Loop device: $dev"
+  sudo rm /dev/mvda && inf "Block device removed"
+  sudo rm /dev/mvda1 && inf "Block device removed"
+  sudo rm /dev/mvda2 && inf "Block device removed"
 
-step "Create a filesystem"
-# mke2fs : Create an ext2/ext3/ext4 filesystem. If called as mkfs.ext3 a journal
-# is created as if the -j option was specified.
-sudo mkfs -t ext3 /dev/mapper/$map
-      
-step "Mount the disk image: disk.img into / as a loop device: /dev/loopN"
+  sudo kpartx -v -d /dev/mapper/vda && inf "Mapper detached"
+  sudo dmsetup remove vda && inf "Mapper detached"
+  sudo kpartx -d $ld  && inf "Mapper detached"
+  sudo losetup -d $ld && inf "Loop device detached" 
+}
+
+# trap cmd to unbind mounted devices on error
+_release_devs_on_err(){
+	local rc=${1:-''}
+	if [[ -z "$rc" ]] ; then
+		rc=$?
+	fi
+  _release_devs
+	local alt_rc=$?
+	(( alt_rc != 0 )) && rc=$alt_rc
+	trap - INT TERM EXIT
+	exit $rc
+}
+
+# Unbind devices on ERROR
+trap _release_devs_on_err INT TERM EXIT
+
+step "Create a loop device and device mappers for the disk"
+
 # Loop devices on Linux are virtual devices which can be used to mount files 
 # like real devices. For instance, to mount an ISO image you can use a loop 
 # device:
 #
-#   $ mkdir -p /mnt/myiso
-#   $ mount -o loop -t iso9660 ./disk.iso /mnt/myiso
+#   $ mkdir -p $wroot/myiso
+#   $ mount -o loop -t iso9660 ./disk.iso $wroot/myiso
 #
 # The parameter -o loop tells mount to mount this as a loop device. For each 
 # mounted loop device a block device file in /dev is used, named /dev/loopN 
@@ -309,11 +335,11 @@ step "Mount the disk image: disk.img into / as a loop device: /dev/loopN"
 # used but you can also specify manually which one to use with losetup command:
 #
 #   $ losetup /dev/loop3 ./disk.iso
-#   $ mount -t iso9660 /dev/loop3 /mnt/myiso
+#   $ mount -t iso9660 /dev/loop3 $wroot/myiso
 #
 # To unmount the ISO file and detatch it from /dev/loop3 run:
 #
-#  $ umount /mnt/myiso
+#  $ umount $wroot/myiso
 #  $ losetup -d /dev/loop3
 #
 # For historical reasons you have 8 such loop devices by default, numbered from 
@@ -327,7 +353,7 @@ step "Mount the disk image: disk.img into / as a loop device: /dev/loopN"
 #
 #  loop max_loop=64
 #
-# In Ubuntu add this to /etc/modprobe.d/options
+# In more recently kernels just add this to /etc/modprobe.d/options
 #
 #  options loop max_loop=64
 #
@@ -335,10 +361,66 @@ step "Mount the disk image: disk.img into / as a loop device: /dev/loopN"
 # mountable loop devices: 
 #
 #  $ ls /dev/loop* | wc -l
-sudo mount -o loop /dev/mapper/$map $wroot
+ld=$(sudo losetup -f --show "$droot"/disk.img)
 
-step "Populate the virtual disk with the system"
-sudo cp -a "$croot"/* "$wroot"
+# creates a device mapper /dev/mapper/vda for the whole disk
+sudo dmsetup create vda << EOT
+0 $(( ${sz} * 2048 )) linear ${ld} 0
+EOT
+
+# Creates device mappers /dev/mapper/vda{1,2} for the {first,second} partition
+# Create device maps from partition tables.
+#  -a     Add partition mappings
+#  -v     Operate verbosely
+sudo kpartx -v -a /dev/mapper/vda
+
+step "Create a block devices directly under /dev"
+
+# See http://savannah.gnu.org/bugs/?27737 
+eval $(stat -c 'major=%t ; minor=%T' $(realpath /dev/mapper/vda))
+sudo mknod /dev/mvda b $(hx2dc $major) $(hx2dc $minor)
+
+eval $(stat -c 'major=%t ; minor=%T' $(realpath /dev/mapper/vda1))
+sudo mknod /dev/mvda1 b $(hx2dc $major) $(hx2dc $minor) 
+
+eval $(stat -c 'major=%t ; minor=%T' $(realpath /dev/mapper/vda2))
+sudo mknod /dev/mvda2 b $(hx2dc $major) $(hx2dc $minor) 
+
+step "Create filesystems and grab UUIDs"
+
+# mke2fs : Create an ext2/ext3/ext4 filesystem. If called as mkfs.ext3 a journal
+# is created as if the -j option was specified.
+sudo mkfs -t ext3 /dev/mvda1
+yes | sudo mkfs -t $rootfs /dev/mvda2
+
+step "Mount and populate the virtual disk with the system"
+
+if [ $(lsb_release -is) = "Debian" ] && [ $rootfs = "ext4" ] ; then
+  # -E test_fs : 
+  #   Set a flag in the filesystem superblock indicating that it may be mounted 
+  # using experimental kernel code, such as the ext4dev filesystem
+  #  
+  # See http://forums.debian.net/viewtopic.php?t=33401
+  sudo tune2fs -E test_fs /dev/mvda2 ;
+  sudo mount -t ext4dev /dev/mvda2 "$wroot" ;
+else
+  sudo mount /dev/mvda2 "$wroot" ;
+fi
+
+# Grab UUIDs
+eval $(sudo blkid -o udev /dev/mvda1)
+VDA1_ID_FS_UUID=${ID_FS_UUID}
+
+# NOTE: blikd shall be executed after tune2fs becaused the UUID is changed! 
+eval $(sudo blkid -o udev /dev/mvda2)
+VDA2_ID_FS_UUID=${ID_FS_UUID}
+
+inf "Copying archives..."
+sudo find "$croot" -mindepth 1 -maxdepth 1 \! -path "$croot"/boot -exec cp -a {} "$wroot" \;
+
+sudo mkdir -p "$wroot"/boot
+sudo mount /dev/mvda1 "$wroot"/boot
+sudo cp -a "$croot"/boot "$wroot"/
 
 # grab locale
 lcl=$(sudo cat "$wroot"/etc/default/locale)
@@ -353,42 +435,89 @@ proc_tzon
 # grab hostname
 c_hn=$(chr cat /etc/hostname)
 
-step "Setup grub device mapping : /boot/grub/device.map"
+step "Setup grub device mapping, load.cfg and grub.cfg. Install GRUB2"
+
 chr << EOT
+mkdir -p /boot/grub
 cat > /boot/grub/device.map << EOF
-(hd0) /dev/sda 
+(hd0) /dev/mvda
+EOF
+cat > /boot/grub/load.cfg << EOF
+search.fs_uuid ${VDA1_ID_FS_UUID} root 
+set prefix=(\$root)/grub
+EOF
+cat > /boot/grub/grub.cfg << EOF
+insmod part_msdos
+insmod ext2
 EOF
 EOT
-device_map=$(mktemp)
-cat > $device_map << EOT
-(hd0) ${droot}/disk.img     
+if [ -n "${GRUB_MODS_PER_FILESYSTEM[$rootfs]}" ] ; then
+  chr << EOT
+cat >> /boot/grub/grub.cfg << EOF
+insmod ${GRUB_MODS_PER_FILESYSTEM[$rootfs]}
+EOF
 EOT
-sudo grub --device-map=$device_map --batch << EOT
-root (hd0,0)
-setup (hd0)
+fi 
+chr << EOT
+cat >> /boot/grub/grub.cfg << EOF
+set root='(hd0,msdos1)'
+search --no-floppy --fs-uuid --set=root ${VDA1_ID_FS_UUID}
+linux /vmlinuz-$(kver) root=UUID=${VDA2_ID_FS_UUID} ro quiet
+initrd /initrd.img-$(kver)
+boot
+EOF
 EOT
 
-step "Configuring GRUB menu.list: /boot/grub/menu.lst"
-# generate GRUB’s menu.lst file  used by the grub bootloader. Looks in /boot for
-# all files which start with "vmlinuz-". They will be treated as kernels, and 
-# grub menu entries will be created for each.  It will  also create the initial 
-# menu.lst if none exists. Also add initrd lines for ramdisk images found with 
-# the same version as kernels found. e.g. /boot/vmlinuz-2.4.5 and 
-# /boot/initrd-2.4.5 will cause a line of "initrd=/boot/initrd-2.4.5 or similar 
-# to be added for the kernel entry in the menu.lst 
-UUID=$(sudo blkid -s UUID -o value /dev/mapper/$map)
-chr sed -i 's/root=UUID=\([a-z0-9-]*\)\(.*\)/root=UUID='$UUID'\2/g' /boot/grub/menu.lst
-chr update-grub || true
-chr grub-set-default 0
-chr sed -ie 's/([^)]*)/(hd0,0)/' /boot/grub/menu.lst
+sudo grub-install --no-floppy --modules="part_msdos ext2 ${GRUB_MODS_PER_FILESYSTEM[$rootfs]}" --root-directory="$wroot" /dev/mvda
+
+step "Generate fstab"
+
+chr << EOT
+cat > /etc/fstab << EOF
+# /etc/fstab: static file system information.
+#
+# Use 'blkid' to print the universally unique identifier for a
+# device; this may be used with UUID= as a more robust way to name devices
+# that works even if disks are added and removed. See fstab(5).
+#
+# <file system> <mount point>   <type>  <options>       <dump>  <pass>
+proc            /proc           proc    defaults        0       0
+# / was on /dev/vda1 during installation
+UUID=${VDA1_ID_FS_UUID} /boot           ext3    noatime,nodev 0       1
+# /boot was on /dev/vda2 during installation
+UUID=${VDA2_ID_FS_UUID} /           ${rootfs}    defaults 0       2
+EOF
+EOT
+
+step "Unpack pending packages"
+
+# Autoremove packages and clean /var/cache/apt/archives first
+apt_get_autoremove
+apt_get_clean
+
+# Move the packages from the pending location to apt cache
+chr << EOT
+mv /var/lib/blss/var/cache/apt/archives/*.deb /var/cache/apt/archives/ 
+EOT
+
+# Filesystems requiere extra packages for self cheking and maintenance
+if [ -n "${EXTRA_PACKAGES_PER_FILESYSTEM[$rootfs]}" ] ; then 
+  apt_get_download ${EXTRA_PACKAGES_PER_FILESYSTEM[$rootfs]}
+fi
+
+# Unpack all the packages and postpone the configuration phase until first boot
+apt_get_unpack_all
+
+# Clears out the local repository of retrieved package files
+inf "Clears out the local repository of retrieved package files at '/var/cache/apt/archives/' and '/var/cache/apt/archives/partial/'"
+apt_get_clean
+apt_get_autoclean
 
 step "Unmount chroot and detach the loop device"
-# Detach the file or device associated with the specified loop device. 
-# See the above explantaion of loop devices
-sudo umount $wroot
-inf "Unmounted $wroot"
-sudo losetup -d $dev
-inf "Loop device detached: "$dev", mapper: "$map 
+_release_devs
+
+# No longer need to release devices on error
+trap - INT TERM EXIT
 
 step "Generates libvirt domain XML defininion file"
 mem_kb=$(( $mem * 1024))
